language: cpp
dist: xenial
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - libgtk-3-dev

script:
  #- sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  #- sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - cd test
  - cmake --version
  - cmake .
  - make
  - ./runTests
