language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
  #- sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  #- sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - cd test
  - cmake --version
  - cmake .
  - make
  - ./runTests
